### ISSUE TITLE
Error for events on weave-gitops HelmRelease page

### ISSUE THREAD

**Issue by rokshana-b** [weaveworks/weave-gitops#1966]
**Describe the bug**

When user navigates from Applications Page to weave-gitops object subpage and looks for events, the page displays error message instead of event list.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/1af19624-12f8-4b7d-a5b1-f883ee33ac40)

**Is this a UI bug or a server bug?**
- [x] UI
- [ ] Server

**What is the severity of the bug**

- [x] `severity/Critical`: Weave GitOps is crashing or experiencing data loss, the UI is inaccessible or a key feature is unusable. There is no known workaround
- [ ] `severity/Major`: Weave Gitops functionality is broken, there is a workaround, but the workaround requires significant effort
- [ ] `severity/Minor`: Weave Gitops functionality is broken, but there is a fairly straightforward workaround
- [ ] `severity/Low`: Doesn’t affect primary flow/functionality but would be good to fix

**Environment**
 - gitops: main
 - How you deployed the Weave GitOps server: Tilt
 - kubernetes:  [e.g. 1.20.4]
    - [x] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_

**To Reproduce**

1. Go to Applications page
2. Click on weave-gitops HelmRelease
3. Navigate to subpage and click on events

**Expected behavior**

Event list should appear just like for any other Applications object.

**Comment by yitsushi** [comment]
I think it's fixed with https://github.com/weaveworks/weave-gitops/pull/2033. That PR fixed the EventTable that's used everywhere.

@rokshana-b : Can you verify that please?

**Comment by josecordaz** [comment]
I just tested this but it seems it is still a problem, I'll take a look

**Comment by josecordaz** [comment]
NVM it seem, this is working properly

**Comment by jpellizzari** [comment]
Looks like we could not reproduce. Closing.

**Comment by rokshana-b** [comment]
Duplicate of #2017
