### ISSUE TITLE
UI is not rendering K8s components for sock-shop on kind cluster

### ISSUE THREAD

**Issue by steveww** [weaveworks/weave-gitops#825]
**Describe the bug**
Sock Shop sample application is deployed on a kind cluster. The UI does not render the K8s components for the application.

**Environment**
 - gitops: [e.g. v0.1.0]
 - kubernetes:  [e.g. 1.20.4]
    - [X] KinD - v0.11.1 go1.16.4 linux/amd64
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: Safari 15.0
 -
**Affects versions**

**To Reproduce**
1. Deploy Sock Shop on KinD cluster using `gitops app add .`

**Expected behavior**
Should see a nice map of K8s components in UI.

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment]
@steveww I need more information. Do the kustomization or source controllers give any kind of error messages? Please add more detail in the form of screen shots or log error messages.

**Comment by steveww** [comment]
Nothing in the logs.

I suspect it's down the K3d Kubernetes cluster. This cluster is running on a EC2 instance and is access via a SSH tunnel through to the K8s API (6443) port.

This is an edge use case but still valid for development and prototyping.

**Comment by jpellizzari** [comment]
@steveww How about a screen shot of the section below the graph?

**Comment by steveww** [comment]
Screenshot to follow.
Just did a fresh install on GKE and it still does not work here.

**Comment by jpellizzari** [comment]
@steveww Can you check your browser console for any errors? Or if this cluster is public-facing, could you give me access to it?

**Comment by steveww** [comment]
I've sent you the details on Slack.

**Comment by jrryjcksn** [comment]
@steveww Do things work for you if you run a KinD cluster locally? I just deployed the sock-shop on my local KinD cluster:

![image](https://user-images.githubusercontent.com/24903211/135933686-7197dc39-2ffb-41fd-978c-52cf4f598f96.png)

**Comment by steveww** [comment]
Interesting. I just tried a `kind` cluster on GCP VM and I get the same result. So I have the same behaviour across k3d, kind and GKE. The common theme being that all are remote.

Looks like the UI only works for locally installed clusters?

**Comment by steveww** [comment]
Just did a fresh install on my Linux laptop with `kind`.
Some minor improvement but still not complete.
![Screenshot from 2021-10-05 12-25-32](https://user-images.githubusercontent.com/5420958/136014651-610230f8-b652-4b8c-8767-e469decb459d.png)

**Comment by jrryjcksn** [comment]
Is your `sock-shop.git` a subset of the `microservices-demo` repository with just the manifests? I'm just wondering about the `./` path...

**Comment by steveww** [comment]
Yes. I created my own repo and just put the manifests in it.

**Comment by jrryjcksn** [comment]
Still working:
![image](https://user-images.githubusercontent.com/24903211/136103518-2352a05a-2226-4bb7-bad1-d3be5cf17809.png)

and I get the same behavior on Firefox and Chrome. I also just tried running with your 33533 port and still everything worked. Your image says "Firefox ESR" but the original bug said "Safari". Do you get the same error with both?

**Comment by jrryjcksn** [comment]
The data comes from a call to the server (GetChildObjects) that just queries the cluster:
```
func (s *applicationServer) GetChildObjects(ctx context.Context, msg *pb.GetChildObjectsReq) (*pb.GetChildObjectsRes, error) {
	list := unstructured.UnstructuredList{}

	list.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   msg.GroupVersionKind.Group,
		Version: msg.GroupVersionKind.Version,
		Kind:    msg.GroupVersionKind.Kind,
	})

	if err := s.kube.List(ctx, &list); err != nil {
		return nil, fmt.Errorf("could not get unstructured object: %s\n", err)
	}

	objects := []*pb.UnstructuredObject{}

Items:
	for _, obj := range list.Items {

		refs := obj.GetOwnerReferences()

		for _, ref := range refs {
			if ref.UID != types.UID(msg.ParentUid) {
				// This is not the child we are looking for.
				// Skip the rest of the operations in Items loops.
				// The is effectively an early return.
				continue Items
			}
		}

		statusResult, err := status.Compute(&obj)
		if err != nil {
			return nil, fmt.Errorf("could not get status for %s: %w", obj.GetName(), err)
		}
		objects = append(objects, &pb.UnstructuredObject{
			GroupVersionKind: &pb.GroupVersionKind{
				Group:   obj.GetObjectKind().GroupVersionKind().Group,
				Version: obj.GetObjectKind().GroupVersionKind().GroupVersion().Version,
				Kind:    obj.GetKind(),
			},
			Name:      obj.GetName(),
			Namespace: obj.GetNamespace(),
			Status:    statusResult.Status.String(),
			Uid:       string(obj.GetUID()),
		})
	}

	return &pb.GetChildObjectsRes{Objects: objects}, nil
}
```
so I don't think it has anything to do with GitHub. There's no debug in the code above; I think the most direct way to see what's coming back is to build the binary with some added debug.

**Comment by steveww** [comment]
Looks like it's just a call to some K8s API. It should just work.

The GitHub auth code thing does not work for me either, so I do not see the commit history.

**Comment by jrryjcksn** [comment]
If you mean from the UI, there is still this comment:
```
//Until the middleware is done this function will not be able to get the token and will fail
func (s *applicationServer) ListCommits(ctx context.Context, msg *pb.ListCommitsRequest) (*pb.ListCommitsResponse, error) {
	providerToken, err := middleware.ExtractProviderToken(ctx)
	if err != nil {
		return nil, grpcStatus.Errorf(codes.Unauthenticated, "error listing commits: %s", err.Error())
	}
```

but you should be able to see it from the CLI. 

Like I said, I think building the code with debug in the object fetching is likely the quickest way to figure out what's failing...

**Comment by steveww** [comment]
I would try to debug this myself but I have no idea how to build and run my own version.

**Comment by jrryjcksn** [comment]
I'll get you a binary

**Comment by jrryjcksn** [comment]
Looks like the UI is working as expected. There was confusion as to where to go for the UI (pod in cluster vs `gitops ui run`).
